/** DO NOT EDIT! This file is generated by @svelte-put/inline-svg vite plugin */
declare module 'svelte/elements' {
	export interface SVGAttributes {
		'inline-src'?:
			| `./${string}`
			| `../${string}`
			| 'svelte'
			| 'google/arrow-right'
			| 'simpleicons/github'
			| 'diagram';
	}
}
export {};
