/** DO NOT EDIT! This file is generated by @svelte-put/inline-svg vite plugin */

export type Source = 
	`./${string}`
	| `../${string}`
	| 'blocks'
	| 'phosphor'
	| 'runes'
	| 'simpleicon'
	| 'svelte-put'
	| 'phosphor/clipboard'
	| 'phosphor/moon-stars'
	| 'phosphor/sliders-horizontal'
	| 'phosphor/sun'
	| 'simpleicon/cloudflare'
	| 'simpleicon/github'
	| 'simpleicon/tailwindcss';
