<script lang="ts">
  import ActionUsageNotice from '$client/components/ActionUsageNotice/ActionUsageNotice.svelte';
  import ApiReference from '$client/components/ApiReference/ApiReference.svelte';
  import ApiUnitReference from '$client/components/ApiUnitReference/ApiUnitReference.svelte';
  import Code from '$client/components/Code/Code.svelte';
  import { ConnectedList, ConnectedListItem } from '$client/components/ConnectedList';
  import Installation from '$client/components/Installation/Installation.svelte';
  import ResourceLink from '$client/components/ResourceLink/ResourceLink.svelte';
  import endImg from '$shared/assets/images/table-of-contents-cat.webp';

  import type { PageData } from './$types';
  import { codes } from './_page/codes';
  export let data: PageData;
</script>

<Installation pkg={data.package.name} />

<section>
  <h2>Introduction</h2>
  <p>
    <code>@svelte-put/toc</code> operates at <strong>runtime</strong> and does the following:
  </p>
  <ConnectedList class="pl-4">
    <ConnectedListItem>
      <p>search for matching elements (default: <code>:where(h1, h2, h3, h4, h5, h6)</code>),</p>
    </ConnectedListItem>
    <ConnectedListItem>
      <p>
        generate <code>id</code> attribute from element content,
      </p>
    </ConnectedListItem>
    <ConnectedListItem>
      <p>add anchor tag to element,</p>
    </ConnectedListItem>
    <ConnectedListItem>
      <p>
        attach <ResourceLink key="IntersectionObserver" /> to each matching element to track its visibility
        on the screen,
      </p>
    </ConnectedListItem>
    <ConnectedListItem>
      <p>expose necessary pieces for building table of contents.</p>
    </ConnectedListItem>
  </ConnectedList>
  <p>
    It is recommended to use the complementary <ResourceLink
      key="@svelte-put/preprocess-auto-slug"
    /> for handling
    <span class="c-circle-number-primary">2</span>
    and
    <span class="c-circle-number-primary">3</span> at <strong>build time</strong> when possible.
    <code>toc</code> will skip those operations if they are already handled by
    <code>preprocess-auto-slug</code>.
  </p>
  <p>
    Notice <code>toc</code> relies on <ResourceLink key="IntersectionObserver" /> and not
    <code>on:scroll</code> for better performance and predictability. See <ResourceLink
      href="https://itnext.io/1v1-scroll-listener-vs-intersection-observers-469a26ab9eb6"
    >
      this article
    </ResourceLink> for a performance comparison between <code>on:scroll</code> vs
    <code>IntersectionObserver</code>.
  </p>

  <p class="c-callout-info">
    The table of contents on this documentation site is generated by <code>toc</code> itself. Check
    out the
    <ResourceLink
      href="https://github.com/vnphanquang/svelte-put/blob/main/apps/docs/src/routes/(main)/+layout.svelte#L223-L227"
    >
      source code here.
    </ResourceLink>
  </p>
</section>

<section>
  <h2 id="quick-start">Quick Start</h2>
  <p>
    Given the following svelte component, let's see how <code>toc</code> searches for all headings,
    generates id based on <code>textContent</code>, adds anchor tag, and tracks active element on
    screen.
  </p>
  <Code code={codes.quickStart.input} title="quick start - input" />
  <p>
    Notice the usage of <code>createTocStore</code> as a helper for creating an idiomatic
    <ResourceLink key="svelte store" />, which will populate its <code>items</code> property with
    the extracted toc elements, and track <code>activeItem</code> if <code>observe</code> is set to
    <code>true</code>.
  </p>
  <Code code={codes.quickStart.output} title="quick start - output" />
</section>

<section>
  <h2>Events</h2>
  <p>
    In <ResourceLink id="quick-start">Quick Start</ResourceLink>,
    <ResourceLink key="svelte store" /> is used to keep code minimal. Alternatively, you can listen for
    <code>tocinit</code> and <code>tocchange</code> events.
  </p>
  <Code code={codes.events} title="events" />
</section>

<section>
  <h2>Toc Action</h2>

  <p>
    <code>use:toc</code> will search for matching elements only from descendants of the element
    where it is used. In the <ResourceLink id="quick-start">Quick Start</ResourceLink> example, that's
    the <code>main</code> element. To search from everything on the page, use it on
    <code>svelte:body</code>.
    <!-- add prop online:boolean to the Code component that renders a minimal box -->
    <Code code={`<svelte:body use:toc />`} />
  </p>

  <ActionUsageNotice action={data.package.id}>
    <h3 slot="heading" let:heading>{heading}</h3>
  </ActionUsageNotice>

  <section>
    <h3>Parameters</h3>
    <p>
      <code>toc</code> is highly customizable. Please visit the extracted
      <ResourceLink
        href="https://github.com/vnphanquang/svelte-put/blob/main/packages/actions/toc/api/docs/toc.tocparameters.md"
      >
        TocParameters
      </ResourceLink> API page for details.
    </p>
  </section>
</section>

<section>
  <h2>Toc Data Attributes</h2>

  <p>
    Attributes listed below can be used to override behavior of <code>toc</code>
    per matching element. All of them are <code>undefined</code> by default.
  </p>

  <ApiUnitReference type="boolean">
    <h3 slot="name"><code>data-toc-ignore</code></h3>
    <p>Whether to ignore this element when searching for matching elements.</p>
  </ApiUnitReference>

  <ApiUnitReference type="string">
    <h3 slot="name"><code>data-toc-id</code></h3>
    <p>
      The <code>id</code> to use for this element in <code>toc</code> context. If not provided, this
      will be the element <code>id</code>, or generated by <code>toc</code>
      if element does not have an <code>id</code> either.
    </p>
  </ApiUnitReference>

  <ApiUnitReference type="'parent' | 'self' | 'auto'">
    <h3 slot="name"><code>data-toc-strategy</code></h3>
    <p>
      Override the <code>strategy</code> for this element to use in creating
      <ResourceLink key="IntersectionObserver" />. This only has effect if the <code>observe</code>
      option is enabled in <code>toc</code> parameters.
    </p>
  </ApiUnitReference>

  <ApiUnitReference type="number">
    <h3 slot="name"><code>data-toc-threshold</code></h3>
    <p>
      Override the <code>threshold</code> for this element to use in creating
      <ResourceLink key="IntersectionObserver" />. This only has effect if the <code>observe</code>
      option is enabled in <code>toc</code> parameters.
    </p>
  </ApiUnitReference>

  <p>
    These attributes are also be referenced from the extracted
    <ResourceLink
      href="https://github.com/vnphanquang/svelte-put/blob/main/packages/actions/toc/api/docs/toc.tocdataattributes"
    >
      TocDataAttributes
    </ResourceLink> API page.
  </p>

  <p>Below instructions show how to add type support for these attributes</p>
  <Code code={codes.dataAttributes} title="app.d.ts" />

  <hr />

  <p>The following attributes act as <strong>readonly</strong> reference markers.</p>

  <ApiUnitReference>
    <h3 slot="name"><code>data-toc</code></h3>
    <p>
      Marking this element that it's been processed by <code>toc</code>.
    </p>
    <p>
      If this is already preprocessed by <ResourceLink key="@svelte-put/preprocess-auto-slug" />,
      there will also be a <code>data-auto-slug</code> attribute.
    </p>
  </ApiUnitReference>

  <ApiUnitReference>
    <h3 slot="name"><code>data-toc-anchor</code></h3>
    <p>
      If the <code>anchor</code> option is enabled in <code>toc</code> parameters, this attribute is
      present on the injected anchor element.
    </p>
    <p>
      If the element is added by <ResourceLink key="@svelte-put/preprocess-auto-slug" />, the
      <code>data-auto-slug-anchor</code> can be seen instead.
    </p>
  </ApiUnitReference>
</section>

<ApiReference href={data.package.apiUrl} />

<img
  src={endImg}
  alt="cat table of contents"
  width="300"
  height="221"
  loading="lazy"
  decoding="async"
/>

<p>Happy making table of contents! 👨‍💻</p>
