/** DO NOT EDIT! This file is generated by @svelte-put/inline-svg vite plugin */
declare module 'svelte/elements' {
	export interface SVGAttributes {
		'inline-src'?:
			| `./${string}`
			| `../${string}`
			| 'blocks'
			| 'phosphor'
			| 'runes'
			| 'simpleicon'
			| 'svelte-put'
			| 'phosphor/archive'
			| 'phosphor/caret-down'
			| 'phosphor/clipboard'
			| 'phosphor/desktop'
			| 'phosphor/drop-half'
			| 'phosphor/envelope-simple'
			| 'phosphor/magnifying-glass'
			| 'phosphor/moon-stars'
			| 'phosphor/sliders-horizontal'
			| 'phosphor/spinner-gap'
			| 'phosphor/status'
			| 'phosphor/sun'
			| 'phosphor/trash'
			| 'phosphor/x'
			| 'phosphor/status/error'
			| 'phosphor/status/info'
			| 'phosphor/status/success'
			| 'phosphor/status/warning'
			| 'simpleicon/cloudflare'
			| 'simpleicon/github'
			| 'simpleicon/tailwindcss';
	}
}
export {};
