name: Changesets
on:
  push:
    branches:
      - main
    paths:
      - '.changeset/**'
      - '.github/workflows/changesets.yaml'
  workflow_dispatch:
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  CI: true
jobs:
  select-mode:
    if: github.repository == 'vnphanquang/svelte-put' # prevents this action from running on forks
    runs-on: ubuntu-latest
    outputs:
      mode: ${{ steps.select-mode.outputs.mode }}
      publish-plan-artifact-id: ${{ steps.select-mode.outputs.publish-plan-artifact-id }}
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Select Changesets mode
        id: select-mode
        uses: changesets/action/select-mode@v2

  version:
    if: needs.select-mode.outputs.mode == 'version'
    needs: select-mode
    runs-on: ubuntu-latest
    outputs:
      version-dir-artifact-id: ${{ steps.version.outputs.version-dir-artifact-id }}
    permissions:
      contents: write # to check out repo (actions/checkout) and commit version changes (changesets/action/version)
      pull-requests: write # to create pull request (changesets/action/version)
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Version packages
        id: version
        uses: changesets/action/version@v2
        with:
          commit-message: 'chore(release): changesets versioning & publication'
          pr-title: 'Changesets: Versioning & Publication'

  pack:
    if: needs.select-mode.outputs.mode == 'publish'
    needs: select-mode
    runs-on: ubuntu-latest
    outputs:
      pack-dir-artifact-id: ${{ steps.pack.outputs.pack-dir-artifact-id }}
    permissions:
      contents: read # to check out repo (actions/checkout)
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        shell: bash
        run: pnpm build

      - name: Pack packages
        id: pack
        uses: changesets/action/pack@v2
        with:
          publish-plan-artifact-id: ${{ needs.select-mode.outputs.publish-plan-artifact-id }}

  publish:
    needs: pack
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write # to check out repo (actions/checkout) and to create releases (changesets/action/publish)
      id-token: write # for trusted publishing (changesets/action/publish)
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Publish packages
        uses: changesets/action/publish@v2
        with:
          pack-dir-artifact-id: ${{ needs.pack.outputs.pack-dir-artifact-id }}
          create-github-releases: true
